### ISSUE TITLE
Login to Google doesn't work ( In new committing)

### ISSUE THREAD

**Issue by metao1** [scrollback/scrollback#935]
Hi guys,
I always check check scrollback, seems there is a problem this time on Google login on  <code>https://scrollback.io/r/google/login </code>
This happened on new commit and it was working fine some days ago.
I debugged the application (google.js) and noticed that the app_id and app_secret read,but action.auth returns null. line 117
I checked it in many environment locally and once I refer to https://scrollback.io/r/google/login and this happened ( just once).

**Comment by aravindet** [comment]
Hi metao1, we found and fixed this problem; it was caused by an incorrect appcache entry. Thanks.

**Comment by aravindet** [comment]
When you visit r/google/login, are you being redirected to Google login page? We had a bug where instead of redirect, it was showing Scrollback UI; this has been fixed.

If this has fixed your problem, please close this issue.

**Comment by metao1** [comment]
Hi Aravin,
Yes the problem is exactly as you mentioned. I pulled today but seems no update came. I cloned from zero and set everything as expected in server-config-defaults.js for Google, but the problem still existed. 
I don't know if I am wrong....

**Comment by aravindet** [comment]
Can you check what branch you are on? You should have received the update if you're on the master branch.

Also, please try clearing your browser's appcache.

**Comment by metao1** [comment]
I checked it and it was master. I cleared all the browser data,also I checked it in other browser type but the problem exists. I run the project instance into a test server so you can check it. here is the address:
https://eclipse-panda-8080.codio.io
Also the codes are available at this [address ](https://codio.com/metao1/chat)
